### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by vukee** [FawadNL/tickera-apple-wallet#1]
Hi,

I want to use this great plugin. The missing part in Tickera.

But it looks like that it does not work with PHP version 7, at least not on 7.2. I did get several warnings on the configuration page like: "Use of undefined constant icon_file - assumed 'icon_file'". After fixing "tc_settings_new_menu_apple_wallet_pass.php" file, I was able to upload at least the icon, pem and cer files.

But after ordering a ticket, the "Wallet Pass" field in the confirmation page stays empty. And no email is sent to the customer anymore. Looks like there is also some script error. But I did not dive deeper into it.

Is there something I am doing wrong?

Thank you,
Ralph

**Comment by FawadNL** [comment]
@vukee can you check your site health and see if you have outdated PHP version or outdated DB? Make sure you are using at least PHP 7.2 and latest stable MySQL DB. 

Also please install the plugin **Error Log Monitor** and enable WP_DEBUG in wp-config to see the exact errors. You can paste the errors related to our plugin here.

**Comment by cybercina** [comment]
on my wallet pass says when i see the order page 

Fatal error: Uncaught TypeError: date_format(): Argument #1 ($object) must be of type DateTimeInterface, string given in /home/bilit/public/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php:149 Stack trace: #0 /home/bilit/public/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php(149): date_format('2024-01-10 19:4...', 'Y-m-d H:i:s') #1 /home/bilit/public/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php(250): appleWalletPass('test', '', '2024-01-10 19:4...', 'vip', '18', '3B645AC401-1', 'sina', 'najafi') #2 /home/bilit/public/wp-content/plugins/tickera/includes/general-functions.php(2931): tc_get_wallet_pass_for_ticket('ticket_apple_wa...', '', 20) #3 /home/bilit/public/wp-content/plugins/tickera/includes/general-functions.php(3043): tc_order_details_table_front(19, false) #4 /home/bilit/public/wp-content/plugins/tickera/includes/templates/page-order.php(46): tc_get_order_details_front('3B645AC401', '1704915857', true) #5 /home/bilit/public/wp-content/plugins/tickera/includes/classes/class.shortcodes.php(502): include('/home/bilit/pub...') #6 /home/bilit/public/wp-includes/shortcodes.php(433): TC_Shortcodes->tc_order_details_page('', '', 'tc_order_detail...') #7 [internal function]: do_shortcode_tag(Array) #8 /home/bilit/public/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(tc_ord...', 'do_shortcode_ta...', '[tc_order_detai...') #9 /home/bilit/public/wp-includes/class-wp-hook.php(324): do_shortcode('[tc_order_detai...') #10 /home/bilit/public/wp-includes/plugin.php(205): WP_Hook->apply_filters('[tc_order_detai...', Array) #11 /home/bilit/public/wp-includes/post-template.php(256): apply_filters('the_content', '[tc_order_detai...') #12 /home/bilit/public/wp-content/themes/eventchamp/page.php(72): the_content() #13 /home/bilit/public/wp-includes/template-loader.php(106): include('/home/bilit/pub...') #14 /home/bilit/public/wp-blog-header.php(19): require_once('/home/bilit/pub...') #15 /home/bilit/public/index.php(17): require('/home/bilit/pub...') #16 {main} thrown in /home/bilit/public/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php on line 149

**Comment by FawadNL** [comment]
@vukee Hi there, have decided to make this an add-on of [commercebird.com](https://commercebird.com) as this was too buggy to do be handled via WP. You simply need a Premium subscription at commercebird and you can set everything up in 5-10 minutes. Plugin is also submitted to wordpress.org so it will become available in the next few weeks. For now you can download the zip from the repo.
