### ISSUE TITLE
PassInvalidException

### ISSUE THREAD

**Issue by 3zero2** [FawadNL/tickera-apple-wallet#10]
I am getting the error below when the code is trying to create the pass. Any tips on what could be wrong please?

Thank you.

`Fatal error: Uncaught Passbook\Exception\PassInvalidException: Failed to validate passbook in /home/mitise5/tickets.mt/wp-content/plugins/Tickera-Apple-Wallet/vendor/eo/passbook/src/Passbook/PassFactory.php:255 Stack trace: #0 /home/mitise5/tickets.mt/wp-content/plugins/Tickera-Apple-Wallet/apple_wallet_pass.php(182): Passbook\PassFactory->package(Object(Passbook\Type\EventTicket), '498D1377D6-1') #1 /home/mitise5/tickets.mt/wp-content/plugins/Tickera-Apple-Wallet/apple_wallet_pass.php(248): appleWalletPass('Corinne Bailey ...', 'Rio Theatre', '2024-05-09 09:0...', 'VIP Seating', '2397', '498D1377D6-1', 'B12') #2 /home/mitise5/tickets.mt/wp-content/plugins/tickera/includes/general-functions.php(2931): tc_get_wallet_pass_for_ticket('ticket_apple_wa...', '', 2497) #3 /home/mitise5/tickets.mt/wp-content/plugins/tickera/includes/general-functions.php(3043): tc_order_details_table_front(2496, false) #4 /home/mitise5/tickets.mt/wp-content/plugins/tickera/includes/templates/page-order.php(46): tc_get_order_details_front('498D1377D6', '1705013377', true) #5 /home/mitise5/tickets.mt/wp-content/plugins/tickera/includes/classes/class.shortcodes.php(502): include('/home/mitise5/t...') #6 /home/mitise5/tickets.mt/wp-includes/shortcodes.php(433): TC_Shortcodes->tc_order_details_page('', '', 'tc_order_detail...') #7 [internal function]: do_shortcode_tag(Array) #8 /home/mitise5/tickets.mt/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(tc_ord...', 'do_shortcode_ta...', '[tc_order_detai...') #9 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(324): do_shortcode('[tc_order_detai...') #10 /home/mitise5/tickets.mt/wp-includes/plugin.php(205): WP_Hook->apply_filters('[tc_order_detai...', Array) #11 /home/mitise5/tickets.mt/wp-includes/post-template.php(256): apply_filters('the_content', '[tc_order_detai...') #12 /home/mitise5/tickets.mt/wp-content/themes/astra/template-parts/single/content-header.php(33): the_content() #13 /home/mitise5/tickets.mt/wp-includes/template.php(792): require('/home/mitise5/t...') #14 /home/mitise5/tickets.mt/wp-includes/template.php(725): load_template('/home/mitise5/t...', false, Array) #15 /home/mitise5/tickets.mt/wp-includes/general-template.php(206): locate_template(Array, true, false, Array) #16 /home/mitise5/tickets.mt/wp-content/themes/astra/inc/template-parts.php(376): get_template_part('template-parts/...') #17 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(324): astra_entry_content_single_page_template('') #18 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #19 /home/mitise5/tickets.mt/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #20 /home/mitise5/tickets.mt/wp-content/themes/astra/inc/core/theme-hooks.php(452): do_action('astra_entry_con...') #21 /home/mitise5/tickets.mt/wp-content/themes/astra/template-parts/content-page.php(26): astra_entry_content_single_page() #22 /home/mitise5/tickets.mt/wp-includes/template.php(792): require('/home/mitise5/t...') #23 /home/mitise5/tickets.mt/wp-includes/template.php(725): load_template('/home/mitise5/t...', false, Array) #24 /home/mitise5/tickets.mt/wp-includes/general-template.php(206): locate_template(Array, true, false, Array) #25 /home/mitise5/tickets.mt/wp-content/themes/astra/inc/class-astra-loop.php(111): get_template_part('template-parts/...', 'page') #26 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(324): Astra_Loop->template_parts_page('') #27 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #28 /home/mitise5/tickets.mt/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #29 /home/mitise5/tickets.mt/wp-content/themes/astra/inc/class-astra-loop.php(199): do_action('astra_page_temp...') #30 /home/mitise5/tickets.mt/wp-content/themes/astra/inc/class-astra-loop.php(176): Astra_Loop->loop_markup(true) #31 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(324): Astra_Loop->loop_markup_page('') #32 /home/mitise5/tickets.mt/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #33 /home/mitise5/tickets.mt/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #34 /home/mitise5/tickets.mt/wp-content/themes/astra/inc/core/theme-hooks.php(267): do_action('astra_content_p...') #35 /home/mitise5/tickets.mt/wp-content/themes/astra/page.php(32): astra_content_page_loop() #36 /home/mitise5/tickets.mt/wp-includes/template-loader.php(106): include('/home/mitise5/t...') #37 /home/mitise5/tickets.mt/wp-blog-header.php(19): require_once('/home/mitise5/t...') #38 /home/mitise5/tickets.mt/index.php(17): require('/home/mitise5/t...') #39 {main} thrown in /home/mitise5/tickets.mt/wp-content/plugins/Tickera-Apple-Wallet/vendor/eo/passbook/src/Passbook/PassFactory.php on line 255`

**Comment by FawadNL** [comment]
@3zero2 Hi there, have decided to make this an add-on of [commercebird.com](https://commercebird.com) as this was too buggy to do be handled via WP. You simply need a Premium subscription at commercebird and you can set everything up in 5-10 minutes. Plugin is also submitted to wordpress.org so it will become available in the next few weeks. For now you can download the zip from the repo.
