### ISSUE TITLE
Fatal error prevents checkout from processing, related to date_format

### ISSUE THREAD

**Issue by WeDigJames** [FawadNL/tickera-apple-wallet#11]
I've just set up this plugin for the first time on a site running latest plugin versions including latest Tickera and Woocommerce.

In my first test, I was not able to complete the checkout - a WooCommerce error displayed, saying "unable to process".

The error log recorded a fatal error. Below is part of that:

`PHP Fatal error:  Uncaught TypeError: date_format(): Argument #1 ($object) must be of type DateTimeInterface, string given in /home/musiquec/public_html/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php:149
Stack trace:
#0 /home/musiquec/public_html/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php(149): date_format('2024-07-31 19:0...', 'Y-m-d H:i:s')
#1 /home/musiquec/public_html/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php(250): appleWalletPass('7PM, 31 July 20...', 'Eglise de Seill...', '2024-07-31 19:0...', 'Concert & prese...', '44953', '22004230MC', NULL, NULL)
#2 /home/musiquec/public_html/wp-content/plugins/tickera/includes/general-functions.php(2706): tc_get_wallet_pass_for_ticket('ticket_apple_wa...', '', 44994)
#3 /home/musiquec/public_html/wp-content/plugins/bridge-for-woocommerce/bridge-for-woocommerce.php(3024): tc_get_tickets_table_email(44993)
...
thrown in /home/musiquec/public_html/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php on line 149
`

Disabled the Apple-Wallet plugin restores my checkout functionality.

Can anyone shed any light on this?
Thanks.

**Comment by FawadNL** [comment]
@WeDigJames Hi there, have decided to make this an add-on of [commercebird.com](https://commercebird.com) as this was too buggy to do be handled via WP. You simply need a Premium subscription at commercebird and you can set everything up in 5-10 minutes. Plugin is also submitted to wordpress.org so it will become available in the next few weeks. For now you can download the zip from the repo.
