### ISSUE TITLE
Uncaught Error: Class "TC_Event" not found

### ISSUE THREAD

**Issue by onmouseout** [FawadNL/tickera-apple-wallet#12]
Hi Roadmap studios, the plugin would be great in my installation - its somehow state-of-the art and im wondering why tickera isnt ofering something out of the box. However, i installed the plugin and created all of the certificates and keys.
The URL to the Apple WWDRCA was updated to:
https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer

After installing and setting everything up, the checkout process breaks at the point where the Pass-Entry is created. The following error is thrown:
```
[29-Oct-2024 20:51:20 UTC] PHP Fatal error:  Uncaught Error: Class "TC_Event" not found in /var/www/web113/htdocs/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php:258
Stack trace:
[...]
#24 /var/www/web113/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#25 /var/www/web113/htdocs/wp-content/plugins/woocommerce-germanized/includes/class-wc-gzd-emails.php(1046): do_action('woocommerce_gzd...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#26 /var/www/web113/htdocs/wp-content/plugins/woocommerce-germanized/includes/class-wc-gzd-emails.php(209): WC_GZD_Emails->confirm_order(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#27 [internal function]: WC_GZD_Emails->after_order_shutdown(358)
#28 {main}
  thrown in /var/www/web113/htdocs/wp-content/plugins/Tickera-Apple-Wallet-master/apple_wallet_pass.php on line 258
```
It looks that maybe something has changed in tickera. Can you have a look?

**Comment by inksplatweb** [comment]
Incase anyone else runs into this problem, TC_Event is now Tickera\TC_Event

**Comment by FawadNL** [comment]
@onmouseout @inksplatweb Hi there, have decided to make this an add-on of [commercebird.com](https://commercebird.com) as this was too buggy to do be handled via WP. You simply need a Premium subscription at commercebird and you can set everything up in 5-10 minutes. Plugin is also submitted to wordpress.org so it will become available in the next few weeks. For now you can download the zip from the repo.
